package yasp:llm;

interface ollama {
    chat: func(json: list<u8>) -> result<list<u8>, string>;
    pull: func(json: list<u8>) -> result<list<u8>, string>;
    delete: func(json: list<u8>) -> result<list<u8>, string>;
    model-list: func() -> result<list<u8>, string>;
}
