apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: exp
  annotations:
    description: "WC"

spec:
  components:
    - name: prv
      type: capability
      properties:
        image: file://./prv/build/bin_prv.par.gz

    - name: cmp
      type: component
      properties:
        image: file://./cmp/build/cmp_s.wasm
      traits:
        - type: spreadscaler
          properties:
            instances: 1

        - type: link
          properties:
            target: prv
            namespace: yasp
            package: llm
            interfaces: [ollama]

        - type: link
          properties:
            target: messaging-nats
            namespace: wasmcloud
            package: messaging
            interfaces: [consumer]

    - name: messaging-nats
      type: capability
      properties:
        image: ghcr.io/wasmcloud/messaging-nats:0.23.1
      traits:
        - type: link
          properties:
            target: cmp
            namespace: wasmcloud
            package: messaging
            interfaces: [handler]
            source_config:
              - name: sub.api
                properties:
                  subscriptions: yasp.boring.api.*
