apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: exp
  annotations:
    description: "WC"

spec:
  components:
    - name: prv
      type: capability
      properties:
        image: file://./prv/build/bin_prv.par.gz

    - name: cmp
      type: component
      properties:
        image: file://./cmp/build/cmp_s.wasm
      traits:
        - type: spreadscaler
          properties:
            instances: 1
        - type: link
          properties:
            target: prv
            namespace: yasp
            package: giga
            interfaces: [wc]

    - name: httpserver
      type: capability
      properties:
        image: ghcr.io/wasmcloud/http-server:0.27.0
      traits:
        - type: link
          properties:
            target:
              name: cmp
            namespace: wasi
            package: http
            interfaces: [incoming-handler]
            source:
              config:
                - name: default-http
                  properties:
                    address: 0.0.0.0:8000
