name = "cmp"
version = "0.1.0"
language = "rust"
type = "component"

[component]
wit_world = "cmp"
wasm_target = "wasm32-wasip2"

[[registry.pull.sources]]
target = "yasp:giga"
source = "file://../shared/interfaces/giga.wit"
