# NOTE: Not yet supported
name = "prv"
language = "go"
type = "provider"
version = "0.1.0"

[provider]
vendor = "yasp"
bin_name = "bin_prv"

[[registry.pull.sources]]
target = "yasp:giga"
source = "file://../shared/interfaces/giga.wit"
